<a href="https://colab.research.google.com/github/HarikrishnanK9/HarikrishnanK9/blob/main/lung_cancer_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/lung_cancer_examples.csv")
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [2]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [3]:
df.duplicated().sum()

0

In [9]:
df1=df.drop(['Name','Surname'],axis=1)
df1

    Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2       6       1
25   21      20      5       3       0
26   37      15      6       2       0
27   34      12      8       0       0
28   55      20      1       4       1
29   40      20      2       7       1
30   36      13      5       2       0
31   56      20      3       3       1
32   47      15      1       8       1
33   62      25      3       4       1
34   26      10      7       2       0
35   25      20      8       2       0
36   59      20      3       4       1
37   62      15      5       5       1
38   33      25      8       2       0
39   37      10      5       3       0
40   50      20      2       4       1
41   47      12      8       0       0
42   69      20      5       4       1
43   63      20      4       5       1
44   39      15      7       2       0
45   21      20      8       3       0
46   31      20      9       4       0
47   28      10      4       1       0
48   53      20      6       3       1
49   62      20      5       6       1
50   42      12      6       2       0
51   44      30      1       6       1
52   26      34      1       8       1
53   35      20      5       1       0
54   26      13      6       1       0
55   77      20      5       4       1
56   75      15      3       5       1
57   43      30      3       8       1
58   51      25      9       0       0

In [12]:
x=df1.iloc[:,:-1].values
x

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],
       [50, 20,  2,  4],
       [47, 12,  8,  0],
       [69, 20,  5,  4],
       [63, 20,  4,  5],
       [39, 15,  7,  2],
       [21, 20,  8,  3],
       [31, 20,  9,  4],
       [28, 10,  4,  1],
       [53, 20,  6,  3],
       [62, 20,  5,  6],
       [42, 12,  6,  2],
       [44, 30,  1,  6],
       [26, 34,  1,  8],
       [35, 20,  5,  1],
       [26, 13,  6,  1],
       [77, 20,  5,  4],
       [75, 15,  3,  5],
       [43, 30,  3,  8],
       [51, 25,  9,  0]])

In [14]:
y=df1.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [23]:
x_train
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [25]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.15393627e+00, -4.32694254e-01,  4.04969135e-01,
        -1.08797778e+00],
       [ 1.77961940e+00, -8.48486388e-01,  8.09938269e-01,
         1.16490550e+00],
       [-5.29775492e-01, -4.32694254e-01,  1.62471662e-17,
        -6.37401124e-01],
       [-1.55279023e-01, -5.71291632e-01,  4.04969135e-01,
        -6.37401124e-01],
       [-3.42527258e-01, -1.55499497e-01,  8.09938269e-01,
        -6.37401124e-01],
       [ 2.02928371e+00,  5.37487393e-01,  1.62471662e-17,
         2.63752189e-01],
       [-3.42527258e-01,  2.60292637e-01,  1.21490740e+00,
        -1.08797778e+00],
       [ 4.68881757e-01,  2.60292637e-01, -4.04969135e-01,
         7.14328846e-01],
       [-6.54607648e-01, -5.71291632e-01,  1.21490740e+00,
        -1.53855444e+00],
       [-4.67359414e-01, -1.55499497e-01,  4.04969135e-01,
        -6.37401124e-01],
       [-1.55279023e-01,  8.14682150e-01, -8.09938269e-01,
         7.14328846e-01],
       [ 2.02928371e+00, -1.81866804e+00, -1.21490740e+00,
         1.16490550e+00],
       [ 1.09304254e+00,  1.23047428e+00, -8.09938269e-01,
         2.63752189e-01],
       [ 1.90445155e+00, -1.55499497e-01, -8.09938269e-01,
         7.14328846e-01],
       [ 1.56801367e-01, -5.71291632e-01,  1.21490740e+00,
        -1.53855444e+00],
       [-1.65326490e+00, -8.48486388e-01,  4.04969135e-01,
        -1.86824467e-01],
       [ 1.56801367e-01, -1.55499497e-01, -1.61987654e+00,
         2.06605882e+00],
       [-1.15393627e+00,  2.47785069e+00, -1.61987654e+00,
         2.06605882e+00],
       [ 3.44049601e-01,  5.37487393e-01, -1.21490740e+00,
         2.63752189e-01],
       [ 1.09304254e+00, -1.55499497e-01,  1.62471662e-17,
         7.14328846e-01],
       [-2.80111180e-01,  5.37487393e-01, -1.21490740e+00,
         1.61548216e+00],
       [ 1.15545862e+00,  5.37487393e-01, -4.04969135e-01,
         7.14328846e-01],
       [-1.09152019e+00,  5.37487393e-01, -1.21490740e+00,
         7.14328846e-01],
       [-7.17023726e-01, -1.12568114e+00,  1.21490740e+00,
        -1.08797778e+00],
       [-9.04271960e-01, -2.23446017e+00,  1.62471662e-17,
        -6.37401124e-01],
       [-8.41855882e-01,  5.37487393e-01,  1.61987654e+00,
         2.63752189e-01],
       [-4.67359414e-01, -8.48486388e-01,  1.62471662e-17,
        -1.86824467e-01],
       [-1.21635235e+00,  5.37487393e-01,  1.21490740e+00,
        -6.37401124e-01],
       [-3.04468673e-02, -1.54147328e+00,  1.21490740e+00,
        -1.08797778e+00],
       [ 5.31297835e-01,  5.37487393e-01,  4.04969135e-01,
        -1.86824467e-01],
       [-7.17023726e-01, -1.68007066e+00,  1.21490740e+00,
        -1.53855444e+00],
       [-1.40360058e+00,  5.37487393e-01,  4.04969135e-01,
        -6.37401124e-01],
       [ 1.09304254e+00, -1.54147328e+00, -4.04969135e-01,
        -1.86824467e-01],
       [ 4.06465679e-01,  1.23047428e+00,  1.61987654e+00,
        -1.53855444e+00],
       [ 6.56129991e-01, -1.55499497e-01, -1.61987654e+00,
        -1.86824467e-01],
       [-1.40360058e+00, -5.71291632e-01,  1.62471662e-17,
        -6.37401124e-01],
       [ 1.52995508e+00,  5.37487393e-01,  1.62471662e-17,
         2.63752189e-01],
       [-6.54607648e-01,  1.23047428e+00, -4.04969135e-01,
         2.06605882e+00],
       [ 6.56129991e-01,  5.37487393e-01, -1.61987654e+00,
         2.63752189e-01],
       [-3.04468673e-02,  1.92346117e+00, -1.61987654e+00,
         1.16490550e+00],
       [-7.17023726e-01,  1.23047428e+00,  1.21490740e+00,
        -6.37401124e-01]])

In [26]:
x_test

array([[-5.92191570e-01, -1.81866804e+00,  1.62471662e-17,
         2.63752189e-01],
       [-6.54607648e-01, -2.23446017e+00,  2.02484567e+00,
        -1.53855444e+00],
       [-1.15393627e+00, -8.48486388e-01,  8.09938269e-01,
        -6.37401124e-01],
       [-1.02910412e+00,  5.37487393e-01, -1.21490740e+00,
         2.06605882e+00],
       [-1.46601666e+00,  5.37487393e-01,  1.21490740e+00,
        -1.86824467e-01],
       [-5.92191570e-01,  5.37487393e-01,  1.62471662e-17,
        -1.08797778e+00],
       [-9.28629454e-02,  1.92346117e+00, -8.09938269e-01,
         2.06605882e+00],
       [-1.46601666e+00,  5.37487393e-01,  1.62471662e-17,
        -1.86824467e-01],
       [-1.02910412e+00, -8.48486388e-01, -4.04969135e-01,
        -1.08797778e+00],
       [-1.21635235e+00, -1.95726541e+00,  1.62471662e-17,
        -1.08797778e+00],
       [ 1.09304254e+00,  5.37487393e-01,  1.62471662e-17,
         1.16490550e+00],
       [-1.02910412e+00, -2.23446017e+00,  1.21490740e+00,
        -1.08797778e+00],
       [ 9.05794304e-01,  5.37487393e-01, -8.09938269e-01,
         2.63752189e-01],
       [ 7.18546069e-01,  5.37487393e-01, -8.09938269e-01,
        -1.86824467e-01],
       [ 3.19692107e-02, -1.95726541e+00,  4.04969135e-01,
        -1.53855444e+00],
       [-1.59084882e+00, -5.71291632e-01,  1.21490740e+00,
        -1.53855444e+00],
       [ 8.43378226e-01, -1.55499497e-01,  2.02484567e+00,
        -1.53855444e+00],
       [ 1.46753901e+00, -1.68007066e+00,  1.62471662e-17,
         1.16490550e+00]])

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [28]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [29]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [34]:
print(knn.predict([[36,13,5,2]]))

[1]

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(score)

0.9444444444444444