<a href="https://colab.research.google.com/github/HarikrishnanK9/HarikrishnanK9/blob/main/Lung_cancer_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/lung_cancer_examples.csv")
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [29]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [30]:
df.duplicated().sum()

0

In [31]:
df1=df.drop(['Name','Surname'],axis=1)
df1

    Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2       6       1
25   21      20      5       3       0
26   37      15      6       2       0
27   34      12      8       0       0
28   55      20      1       4       1
29   40      20      2       7       1
30   36      13      5       2       0
31   56      20      3       3       1
32   47      15      1       8       1
33   62      25      3       4       1
34   26      10      7       2       0
35   25      20      8       2       0
36   59      20      3       4       1
37   62      15      5       5       1
38   33      25      8       2       0
39   37      10      5       3       0
40   50      20      2       4       1
41   47      12      8       0       0
42   69      20      5       4       1
43   63      20      4       5       1
44   39      15      7       2       0
45   21      20      8       3       0
46   31      20      9       4       0
47   28      10      4       1       0
48   53      20      6       3       1
49   62      20      5       6       1
50   42      12      6       2       0
51   44      30      1       6       1
52   26      34      1       8       1
53   35      20      5       1       0
54   26      13      6       1       0
55   77      20      5       4       1
56   75      15      3       5       1
57   43      30      3       8       1
58   51      25      9       0       0

In [32]:
x=df1.iloc[:,:-1].values
x

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],
       [50, 20,  2,  4],
       [47, 12,  8,  0],
       [69, 20,  5,  4],
       [63, 20,  4,  5],
       [39, 15,  7,  2],
       [21, 20,  8,  3],
       [31, 20,  9,  4],
       [28, 10,  4,  1],
       [53, 20,  6,  3],
       [62, 20,  5,  6],
       [42, 12,  6,  2],
       [44, 30,  1,  6],
       [26, 34,  1,  8],
       [35, 20,  5,  1],
       [26, 13,  6,  1],
       [77, 20,  5,  4],
       [75, 15,  3,  5],
       [43, 30,  3,  8],
       [51, 25,  9,  0]])

In [33]:
y=df.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [35]:
x_train

array([[26, 13,  6,  1],
       [73, 10,  7,  6],
       [36, 13,  5,  2],
       [42, 12,  6,  2],
       [39, 15,  7,  2],
       [77, 20,  5,  4],
       [39, 18,  8,  1],
       [52, 18,  4,  5],
       [34, 12,  8,  0],
       [37, 15,  6,  2],
       [42, 22,  3,  5],
       [77,  3,  2,  6],
       [62, 25,  3,  4],
       [75, 15,  3,  5],
       [47, 12,  8,  0],
       [18, 10,  6,  3],
       [47, 15,  1,  8],
       [26, 34,  1,  8],
       [50, 20,  2,  4],
       [62, 15,  5,  5],
       [40, 20,  2,  7],
       [63, 20,  4,  5],
       [27, 20,  2,  5],
       [33,  8,  8,  1],
       [30,  0,  5,  2],
       [31, 20,  9,  4],
       [37, 10,  5,  3],
       [25, 20,  8,  2],
       [44,  5,  8,  1],
       [53, 20,  6,  3],
       [33,  4,  8,  0],
       [22, 20,  6,  2],
       [62,  5,  4,  3],
       [51, 25,  9,  0],
       [55, 15,  1,  3],
       [22, 12,  5,  2],
       [69, 20,  5,  4],
       [34, 25,  4,  8],
       [55, 20,  1,  4],
       [44, 30,  1,  6],
       [33, 25,  8,  2]])

In [36]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [37]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [38]:
x_train

array([[-1.15393627, -0.43269425,  0.40496913, -1.08797778],
       [ 1.7796194 , -0.84848639,  0.80993827,  1.1649055 ],
       [-0.52977549, -0.43269425,  0.        , -0.63740112],
       [-0.15527902, -0.57129163,  0.40496913, -0.63740112],
       [-0.34252726, -0.1554995 ,  0.80993827, -0.63740112],
       [ 2.02928371,  0.53748739,  0.        ,  0.26375219],
       [-0.34252726,  0.26029264,  1.2149074 , -1.08797778],
       [ 0.46888176,  0.26029264, -0.40496913,  0.71432885],
       [-0.65460765, -0.57129163,  1.2149074 , -1.53855444],
       [-0.46735941, -0.1554995 ,  0.40496913, -0.63740112],
       [-0.15527902,  0.81468215, -0.80993827,  0.71432885],
       [ 2.02928371, -1.81866804, -1.2149074 ,  1.1649055 ],
       [ 1.09304254,  1.23047428, -0.80993827,  0.26375219],
       [ 1.90445155, -0.1554995 , -0.80993827,  0.71432885],
       [ 0.15680137, -0.57129163,  1.2149074 , -1.53855444],
       [-1.6532649 , -0.84848639,  0.40496913, -0.18682447],
       [ 0.15680137, -0.1554995 , -1.61987654,  2.06605882],
       [-1.15393627,  2.47785069, -1.61987654,  2.06605882],
       [ 0.3440496 ,  0.53748739, -1.2149074 ,  0.26375219],
       [ 1.09304254, -0.1554995 ,  0.        ,  0.71432885],
       [-0.28011118,  0.53748739, -1.2149074 ,  1.61548216],
       [ 1.15545862,  0.53748739, -0.40496913,  0.71432885],
       [-1.09152019,  0.53748739, -1.2149074 ,  0.71432885],
       [-0.71702373, -1.12568114,  1.2149074 , -1.08797778],
       [-0.90427196, -2.23446017,  0.        , -0.63740112],
       [-0.84185588,  0.53748739,  1.61987654,  0.26375219],
       [-0.46735941, -0.84848639,  0.        , -0.18682447],
       [-1.21635235,  0.53748739,  1.2149074 , -0.63740112],
       [-0.03044687, -1.54147328,  1.2149074 , -1.08797778],
       [ 0.53129784,  0.53748739,  0.40496913, -0.18682447],
       [-0.71702373, -1.68007066,  1.2149074 , -1.53855444],
       [-1.40360058,  0.53748739,  0.40496913, -0.63740112],
       [ 1.09304254, -1.54147328, -0.40496913, -0.18682447],
       [ 0.40646568,  1.23047428,  1.61987654, -1.53855444],
       [ 0.65612999, -0.1554995 , -1.61987654, -0.18682447],
       [-1.40360058, -0.57129163,  0.        , -0.63740112],
       [ 1.52995508,  0.53748739,  0.        ,  0.26375219],
       [-0.65460765,  1.23047428, -0.40496913,  2.06605882],
       [ 0.65612999,  0.53748739, -1.61987654,  0.26375219],
       [-0.03044687,  1.92346117, -1.61987654,  1.1649055 ],
       [-0.71702373,  1.23047428,  1.2149074 , -0.63740112]])

In [39]:
x_test

array([[-0.59219157, -1.81866804,  0.        ,  0.26375219],
       [-0.65460765, -2.23446017,  2.02484567, -1.53855444],
       [-1.15393627, -0.84848639,  0.80993827, -0.63740112],
       [-1.02910412,  0.53748739, -1.2149074 ,  2.06605882],
       [-1.46601666,  0.53748739,  1.2149074 , -0.18682447],
       [-0.59219157,  0.53748739,  0.        , -1.08797778],
       [-0.09286295,  1.92346117, -0.80993827,  2.06605882],
       [-1.46601666,  0.53748739,  0.        , -0.18682447],
       [-1.02910412, -0.84848639, -0.40496913, -1.08797778],
       [-1.21635235, -1.95726541,  0.        , -1.08797778],
       [ 1.09304254,  0.53748739,  0.        ,  1.1649055 ],
       [-1.02910412, -2.23446017,  1.2149074 , -1.08797778],
       [ 0.9057943 ,  0.53748739, -0.80993827,  0.26375219],
       [ 0.71854607,  0.53748739, -0.80993827, -0.18682447],
       [ 0.03196921, -1.95726541,  0.40496913, -1.53855444],
       [-1.59084882, -0.57129163,  1.2149074 , -1.53855444],
       [ 0.84337823, -0.1554995 ,  2.02484567, -1.53855444],
       [ 1.46753901, -1.68007066,  0.        ,  1.1649055 ]])

In [41]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(result,score)

[[11  0]
 [ 1  6]] 0.9444444444444444